/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.file.upload.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeDetail service. Represents a row in the &quot;employee_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.file.upload.model.impl.EmployeeDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.file.upload.model.impl.EmployeeDetailImpl}.
 * </p>
 *
 * @author ChiragSoni
 * @see EmployeeDetail
 * @see com.file.upload.model.impl.EmployeeDetailImpl
 * @see com.file.upload.model.impl.EmployeeDetailModelImpl
 * @generated
 */
public interface EmployeeDetailModel extends BaseModel<EmployeeDetail>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee detail model instance should use the {@link EmployeeDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this employee detail.
	 *
	 * @return the primary key of this employee detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee detail.
	 *
	 * @param primaryKey the primary key of this employee detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this employee detail.
	 *
	 * @return the employee ID of this employee detail
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee detail.
	 *
	 * @param employeeId the employee ID of this employee detail
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the first name of this employee detail.
	 *
	 * @return the first name of this employee detail
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this employee detail.
	 *
	 * @param firstName the first name of this employee detail
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this employee detail.
	 *
	 * @return the last name of this employee detail
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this employee detail.
	 *
	 * @param lastName the last name of this employee detail
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the group ID of this employee detail.
	 *
	 * @return the group ID of this employee detail
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee detail.
	 *
	 * @param groupId the group ID of this employee detail
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee detail.
	 *
	 * @return the company ID of this employee detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee detail.
	 *
	 * @param companyId the company ID of this employee detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee detail.
	 *
	 * @return the user ID of this employee detail
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee detail.
	 *
	 * @param userId the user ID of this employee detail
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee detail.
	 *
	 * @return the user uuid of this employee detail
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee detail.
	 *
	 * @param userUuid the user uuid of this employee detail
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee detail.
	 *
	 * @return the user name of this employee detail
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee detail.
	 *
	 * @param userName the user name of this employee detail
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee detail.
	 *
	 * @return the create date of this employee detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee detail.
	 *
	 * @param createDate the create date of this employee detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee detail.
	 *
	 * @return the modified date of this employee detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee detail.
	 *
	 * @param modifiedDate the modified date of this employee detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.file.upload.model.EmployeeDetail employeeDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.file.upload.model.EmployeeDetail> toCacheModel();

	@Override
	public com.file.upload.model.EmployeeDetail toEscapedModel();

	@Override
	public com.file.upload.model.EmployeeDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}